# Default values for account-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/army-telegram-bots/react-account/react-account
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: 
  - name: regcred
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 80

metrics:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi

probes:
  livenessProbe:
    httpGet:
      path: /healthchecks
      port: 3000
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 10
  readinessProbe:
    httpGet:
      path: /healthchecks
      port: 3000
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 10

nodeSelector: {}

tolerations: []

affinity: {}
